[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm ci --include=dev']

[phases.build]
cmds = ['npm run build', 'npx prisma generate']

[start]
cmd = 'npm start'